[package]
name = "aoc_2020"
version = "0.0.1"
authors = ["F0X <f0xde@protonmail.com>"]
edition = "2018"
repository = "https://github.com/F0Xde/aoc_2020"
license = "Unlicense"
publish = false

[dependencies]
aoc-runner = "0.3"
aoc-runner-derive = "0.3"
